const data=[
    {id:1,
        title:"Netflix Original Series",
        link:"./bad.jpg",
        Name:"Breaking Bad",
        date:"jan 2010",
        redirect:"https://www.netflix.com/search?q:breaki&jbv:70143836"
    },
    {id:2,
        title:"Netflix Original Series",
        link:"./luc.webp",
        Name:"Lucifer",
        date:"Nov 20",
        redirect:"https://www.netflix.com/search?q=lucifer&jbv=80057918",
    },
    {id:3,
        title:"Netflix Original Series",
        link:"./dark.jpg",
        Name:"Dark",
        date:"july 19",
        redirect:"https://www.netflix.com/search?q:dark&jbv:80100172",
    },
    {id:4,
        title:"Netflix Original Series",
        link:"./moneyheist.png",
        Name:"Money Heist",
        date:"june 20",
        redirect:"https://www.netflix.com/search?q:money%20h&jbv:80192098"
    },
    {id:5,
        title:"Netflix Original Series",
        link:"./strangerthings.jpeg",
        Name:"Stranger things",
        date:"jan 17",
        redirect:"https://www.netflix.com/search?q:stranger&jbv:80057281"
    },
    {id:6,
        title:"Netflix Original Series",
        link:"./lost.webp",
        Name:"Lost In Space",
        date:"dec 18",
        redirect:"https://www.netflix.com/search?q:lost&jbv:80104198"
    },
    {id:7,
        title:"Netflix Original Series",
        link:"./peaky.jpg",
        Name:"Peaky Blinders",
        date:"july 04",
        redirect:"https://www.netflix.com/search?q:peaky&jbv:80002479"
    },
    {id:8,
        title:"Netflix Original Series",
        link:"./umbrella.jpg",
        Name:"Umbrella Academy",
        date:"may 21",
        redirect:"https://www.netflix.com/search?q:umbrel&jbv:80186863"
    },
    {id:9,
        title:"Netflix Original Series",
        link:"./big.jpg",
        Name:"Big Bang Theory",
        date:"feb 15",
        redirect:"https://www.netflix.com/search?q:big%20bang&jbv:70143830"
    },
    {   id:10,
        title:"Netflix Original Series",
        link:"./game.jpg",
        Name:"Squid Game",
        date:"oct 22",
        redirect:"https://www.netflix.com/browse/genre/83?jbv:81040344"
    }
]


export default data